# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

---
name: Build app

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "*.md"
      - "*.txt"
      - .editorconfig
      - .github/**
      - .gitignore
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - run: dotnet test
  deploy:
    name: Publish application
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/') && success()
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - run: |
          echo "Github ref is: $GITHUB_REF"
          if [[ "$GITHUB_REF" =~ ^refs\/tags\/([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+(\-[[:alpha:]])?)$ ]]; then
            echo "Version is: ${BASH_REMATCH[1]}"
            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            >&2 echo "Not running for a tag. Is this a problem with Github Actions?"
            exit 1
          fi
        name: Prepare version number
      - run: dotnet pack ICantBelieveItsCrypto -p:Version=$VERSION
        name: NuGet Pack
      - name: Publish package to nuget.org
        run: dotnet nuget push ICantBelieveItsCrypto/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
